version: 2.1

references:
  images:
    middleman: &MIDDLEMAN_IMAGE docker.mirror.hashicorp.services/hashicorp/middleman-hashicorp:0.3.44
    ubuntu: &UBUNTU_IMAGE ubuntu-1604:201903-01

  cache:
    rubygem: &RUBYGEM_CACHE_KEY static-site-gems-v1-{{ checksum "content/Gemfile.lock" }}

jobs:
  website-test:
    machine:
      image: *UBUNTU_IMAGE
    steps:
      - checkout

      - run:
          name: gem and bundle install
          command: |
            gem install bundler -v '1.17.3' --no-document
            bundle _1.17.3_ install --jobs=3 --retry=3

      - run: make sync

      - run: make website-test

  website-build-and-upload:
    docker:
      - image: *MIDDLEMAN_IMAGE
    steps:
      - checkout

      # pull and update git submodules
      - run: make sync

      # restores gem cache
      - restore_cache:
          key: *RUBYGEM_CACHE_KEY

      - run:
          name: install gems
          working_directory: content
          command: bundle check || bundle install --path vendor/bundle --retry=3

      # saves gem cache if we have changed the Gemfile
      - save_cache:
          key: *RUBYGEM_CACHE_KEY
          paths:
            - content/vendor/bundle

      - run:
          name: middleman build
          working_directory: content
          command: bundle exec middleman build

      - run:
          working_directory: content
          command: ./scripts/upload.sh

  website-warm-cache-check-links:
    docker:
      - image: *MIDDLEMAN_IMAGE
    steps:
      # Don't need gems or anything
      - run:
          name: Warm cache and check for broken links
          command: wget --delete-after --level inf --no-directories --no-host-directories --no-verbose --page-requisites --recursive --spider "https://www.terraform.io/"


workflows:
  linkcheck:
    # run on branches and PRs; ignore master, since the cache warming also checks links.
    jobs:
      - website-test:
        filters:
          branches:
            ignore: master
  website-deploy:
    # only run on main branch
    jobs:
      - website-build-and-upload:
          context: static-sites
          filters:
            branches:
              only: master
      - website-warm-cache-check-links:
          context: static-sites
          filters:
            branches:
              only: master
          requires:
            - website-build-and-upload
